apiVersion: batch/v1
kind: Job
metadata:
  name: nemo-redux-detector-suite
spec:
  template:
    spec:
      nodeSelector:
        springfield.uit.no/gpu-type: titan-xp
      containers:
      - name: nemo-redux-detector-suite
        image: thomasjo/nemo-redux:detection
        imagePullPolicy: Always
        workingDir: /storage/nemo-redux
        command: ["bash", "scripts/detector_suite"]
        stdin: true
        tty: true
        envFrom:
        - secretRef:
            name: wandb
        volumeMounts:
        - name: storage
          mountPath: /storage
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: storage
        persistentVolumeClaim:
            claimName: storage
      - name: shm
        emptyDir:
          medium: Memory
      restartPolicy: OnFailure
  backoffLimit: 0
