apiVersion: batch/v1
kind: Job
metadata:
  name: nemo-redux-detector
spec:
  template:
    spec:
      nodeSelector:
        springfield.uit.no/gpu-type: titan-xp
      containers:
      - name: nemo-redux-detector
        image: thomasjo/nemo-redux:detection
        imagePullPolicy: Always
        workingDir: /storage/nemo-redux
        command:
        - python
        - src/train_detector.py
        - --output-dir=output/detection
        - --num-workers=1
        - --seed=42
        stdin: true
        tty: true
        envFrom:
        - secretRef:
            name: wandb
        volumeMounts:
        - name: storage
          mountPath: /storage
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: storage
        persistentVolumeClaim:
            claimName: storage
      - name: shm
        emptyDir:
          medium: Memory
      restartPolicy: OnFailure
  backoffLimit: 0
