#!/usr/bin/env bash

set -eu

function contains() {
  local array="$1[@]"
  local seeking="$2"
  local not_found=1

  for elem in "${!array}"; do
    if [[ $elem == "$seeking" ]]; then
      not_found=0
      break
    fi
  done

  return $not_found
}

allowlist=(
  # "2019-06"
  # "2020-05"
  "2020-07"
)

# 2019-06
# -------
if [[ " ${allowlist[*]} " =~ "2019-06" ]]; then
  # dims: [3772, 3602]
  # mean: 3687

  # Agglutinated
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2019-06/agglutinated \
    --output-dir output/objects/2019-06/agglutinated \
    --corner-margin 400 \
    --object-blur 31 \
    --debug

  # Benthic
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2019-06/benthic \
    --output-dir output/objects/2019-06/benthic \
    --corner-margin 400 \
    --object-blur 31 \
    --debug

  # Planktic
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2019-06/planktic \
    --output-dir output/objects/2019-06/planktic \
    --corner-margin 400 \
    --object-blur 31 \
    --debug

  # Sediment
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2019-06/sediment \
    --output-dir output/objects/2019-06/sediment \
    --corner-margin 400 \
    --object-blur 31 \
    --debug
fi


# 2020-05
# -------
if contains allowlist "2020-05"; then
  # dims: [3694, 3596]
  # mean: 3645

  # Benthic
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2020-05/benthic \
    --output-dir output/objects/2020-05/benthic \
    --border-blur 0 \
    --corner-margin 500 \
    --object-threshold 90 \
    --debug

  # Planktic
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2020-05/planktic \
    --output-dir output/objects/2020-05/planktic \
    --border-blur 0 \
    --corner-margin 500 \
    --object-threshold 90 \
    --debug
fi

# 2020-07
# -------
if contains allowlist "2020-07"; then
  # dims: [8745, 9151]
  # mean: 8948
  #
  # scale: (8948 / 3687) ≃ 2.43
  #
  # patch size: 224 * scale ≃ 544
  # patch size: 256 * scale ≃ 622

  # Agglutinated
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2020-07/agglutinated \
    --output-dir output/objects/2020-07/agglutinated \
    --min-pixel-count 2048 \
    --border-blur 0 \
    --corner-margin 1000 \
    --edge-margin 296 \
    --object-blur 27 \
    --object-threshold 60 \
    --debug

  # Benthic
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2020-07/benthic \
    --output-dir output/objects/2020-07/benthic \
    --min-pixel-count 2048 \
    --border-blur 0 \
    --corner-margin 1000 \
    --edge-margin 296 \
    --object-blur 27 \
    --object-threshold 65 \
    --debug

  # Planktic
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2020-07/planktic \
    --output-dir output/objects/2020-07/planktic \
    --min-pixel-count 2048 \
    --border-blur 0 \
    --corner-margin 1000 \
    --edge-margin 296 \
    --object-blur 27 \
    --object-threshold 70 \
    --debug

  # Sediment
  python src/nemo/preprocessing/extract_masks.py \
    --source-dir data/raw/2020-07/sediment \
    --output-dir output/objects/2020-07/sediment \
    --min-pixel-count 2048 \
    --border-blur 0 \
    --corner-margin 1000 \
    --edge-margin 296 \
    --object-blur 27 \
    --object-threshold 55 \
    --debug
fi
